### PR TITLE
UI: Navigation Bar and React Router

### LINKED ISSUE #19: 🚀 - Navigation Bar
# 🚀 feature request

**Is your feature request related to a problem? Please describe.**

A navigation bar is needed. One that will contain

- [x] Title / Logo of the website
- [x] A `Menu` button that activates a Navigation Drawer
- [x] A user account menu button (links to `Account Dashboard` and has a `Logout` button)
  - [ ] Account Dashboard button
  - [ ] Logout button
- [x] A `Cart` button

**Describe the solution you'd like**

This page should be built and styled using Material-UI components.

### PR DESCRIPTION
**Pull request by davidsaulrodriguez**
## Proposed changes

This Pull Request adds the `react-router-dom` package to the project and also enables the Router in the app.

## PR Checklist

- [X] I have read the [CONTRIBUTING](https://github.com/davidsaulrodriguez/shop-portal/blob/master/CONTRIBUTING.md) doc
- [X] I have read the [BRANCHING MODEL](https://github.com/davidsaulrodriguez/shop-portal/blob/master/BRANCHINGMODEL.md) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## PR Type

What types of changes does your code introduce to **Shop Portal**?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code Style Update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (Please describe):

## Current behavior

Issue Number: #19

## New behavior

Fixes #19

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Further comments

This pull request touches both the frontend and backend files. The front end files touched are simply the `package.json` and `package-lock.json` files from installing the `react-router-dom` npm package.

Other than that, the rest of this pull request needs to be reviewed by the front end team.

### CODE REVIEW

**Review by jdavidrice — APPROVED** [review]
LGTM

**Comment by davidsaulrodriguez** [comment]
Even though this branch doesn't actually require a review, I am still requesting one last code review and approval from either @pennyquirino or @Mconway409 in order to get this completely merged.

**Review by jdavidrice — CHANGES_REQUESTED** [review]
I pulled this code down and tested it out with my sign in page, and it works fine - but the unit test App.test.js fails. The first error it gave was "Error: Uncaught [Error: Invariant failed: You should not use <withRouter(Navigation) /> outside a <Router>] ." I fixed it by removing withRouter from Navigation.jsx. Then it threw: "Error: Uncaught [Error: Invariant failed: You should not use <withRouter(NavigationDrawer) /> outside a <Router>]," and I fixed that by removing withRouter from NavigationDrawer.jsx. Then it threw: "Error: Uncaught [TypeError: Cannot read property 'location' of undefined]" and I fixed that by removing  useLocation from NavigationDrawer.jsx. Page loads and tests pass, but I'm sure that we need withRouter and useLocation - so how should we make this work?

**Comment by davidsaulrodriguez** [comment]
> I pulled this code down and tested it out with my sign in page, and it works fine - but the unit test App.test.js fails. The first error it gave was "Error: Uncaught [Error: Invariant failed: You should not use <withRouter(Navigation) /> outside a ] ." I fixed it by removing withRouter from Navigation.jsx. Then it threw: "Error: Uncaught [Error: Invariant failed: You should not use <withRouter(NavigationDrawer) /> outside a ]," and I fixed that by removing withRouter from NavigationDrawer.jsx. Then it threw: "Error: Uncaught [TypeError: Cannot read property 'location' of undefined]" and I fixed that by removing useLocation from NavigationDrawer.jsx. Page loads and tests pass, but I'm sure that we need withRouter and useLocation - so how should we make this work?

Thank you for pointing this out! I will fix this ASAP!

**Pull request merged**
